name: Node.js CI

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches: [ "master", "staging" ]
  pull_request:
    branches: [ "master", "staging", "dev" ]

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install moules
        run: |
          npm install -g pnpm
          pnpm install
      - name: Check project
        run: pnpm run check
